### ISSUE TITLE
Just Your Type Rational 

### ISSUE THREAD

**Issue by sent0007** [sent0007/just-your-type#1]
My concept is based around a quote website. This would be an example of one of the pages that you would be created for a famous quote. I chose to do a quote on problem solving given its relevance in our industry. The quote was first published in a physics publication and this is where I found the inspiration for the header text, which was printed on the cover seen below. I adjusted the tracking to match accordingly. I paired the body copy with PT sans because  of its readability and its contrast to the header font. I chose the golden ratio because of the large difference between each heading size. I chose a soft complementary color scheme with a gradient to add some color interest  repetition and harmony. I effectively used modular CSS with the button's distribution and aligning elements on the page. I wanted an element to be offset to balance out the header text and to help guide the eye down the page but I couldn't correctly do it with grids so I took another approach and used a module.css class and used absolute positioning.

I apologize for the late entry and message. I cheated on the quotes and used SVG file icons so I am unable to submit through markbot. Below is the screen shot.

thanks,

Curtis Sentner
Group 4

![external-content duckduckgo](https://user-images.githubusercontent.com/55108791/76587994-25db9c00-64bc-11ea-83f5-d169a3b1e891.gif)

![Screen Shot 2020-03-12 at 11 45 12 PM](https://user-images.githubusercontent.com/55108791/76587959-0d6b8180-64bc-11ea-991e-564f6620899d.png)

@muxlowc

**Comment by muxlowc** [comment]
@sent0007 No worries, I'll give you the markbot mark :)
